import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Providers } from "./providers";
import clsx from "clsx";

const inter = Roboto({
  display: "swap",
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: `Default`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={clsx(inter.className, "dark:bg-[#121212]")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
